import os

def get_yaml_example_of_app(path):
    with open(os.path.join(path,'parameter.yaml'), 'w', encoding="utf-8") as f:
        f.write("#设备信息")
        f.write('\n')
        f.write("desired_caps:")
        f.write('\n')
        f.write("  platformName: android")
        f.write('\n')
        f.write("  platformVersion: 10")
        f.write('\n')
        f.write("  deviceName: MGFVB20908005234")
        f.write('\n')
        f.write("  appPackage: com.livibank.hk")
        f.write('\n')
        f.write("  appActivity: com.jd.jr.common.splash.activity.LaunchActivity")
        f.write('\n')
        f.write("  #autoLaunch为True时会重启app，False时不重启app，可在app继续执行步骤(仅限安卓)")
        f.write('\n')
        f.write("  autoLaunch: true")
        f.write('\n')
        f.write("  #noReset为False时会重启app，True时不重启app，可在app继续执行步骤(仅限ios)")
        f.write('\n')
        f.write("  noReset: true")
        f.write('\n')
        f.write("  udid: 12A957BF-4ED8-4F22-A928-3790B3B69205")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("#设备语言 (简体：SimplifiedChinese；繁体：TraditionalChinese；英文：English)，autoLaunch为false生效,noReset为true生效")
        f.write('\n')
        f.write("language: SimplifiedChinese")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("#App测试环境")
        f.write('\n')
        f.write("Science: UAT2")
        f.write('\n')
        f.write("#填写new代表新版本，不填则代表旧版本")
        f.write('\n')
        f.write("Version: NEW")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("#L2账号")
        f.write('\n')
        f.write("phone_L2: 55674562")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("#L3账号")
        f.write('\n')
        f.write("phone_L3: 48924771")
        f.write('\n')
        f.write("password: Aa123456")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("#流动保安编码")
        f.write('\n')
        f.write("sotfTokenPIN: 147258")

def get_yaml_example_of_web(path):
    with open(os.path.join(path, 'parameter.yaml'), 'w', encoding="utf-8") as f:
        f.write("#XXX项目参数")
        f.write('\n')
        f.write("XXX:")
        f.write('\n')
        f.write("  url: 请填写项目地址")
        f.write('\n')

def get_yaml_example_of_app_element(path):
    with open(os.path.join(path, 'AppSettingElement.yaml'), 'w', encoding="utf-8") as f:
        f.write("#App设置页元素")
        f.write('\n')
        f.write("AppSettingPage:")
        f.write('\n')
        f.write("  android:")
        f.write('\n')
        f.write("    #语言下拉框")
        f.write('\n')
        f.write("    languageElement: //android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[2]/android.view.View[1]")
        f.write('\n')
        f.write("    #语言选择")
        f.write('\n')
        f.write("    EnglishElement: //*[contains(@content-desc, 'English')]")
        f.write('\n')
        f.write("    SimplifiedChineseElement: //*[contains(@content-desc, '简体中文')]")
        f.write('\n')
        f.write("    TraditionalChineseElement: //*[contains(@content-desc, '繁體中文')]")
        f.write('\n')
        f.write("    #通知按钮")
        f.write('\n')
        f.write("    notificationsElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '通知')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '通知')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Notifications')]")
        f.write('\n')
        f.write("    #登录设置按钮")
        f.write('\n')
        f.write("    loginSettingsElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '登录设置')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '登入設定')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Login Settings')]")
        f.write('\n')
        f.write("    #更改登录密码")
        f.write('\n')
        f.write("    Changeloginpassword:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '更改登录密码')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '更改登入密碼')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Change Login Password')]")
        f.write('\n')
        f.write("    #流动保安编码按钮")
        f.write('\n')
        f.write("    softTokenSettingsElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '流动保安编码')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '流動保安編碼')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Soft Token')]")
        f.write('\n')
        f.write("    #流动保安编码开关元素")
        f.write('\n')
        f.write("    softTokenSwitchElement: //android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[2]/android.widget.Switch[1]")
        f.write('\n')
        f.write("    #关闭保安流动编码弹窗确认元素")
        f.write('\n')
        f.write("    closeSoftTokenSwitchElement_YES:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '是')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '是')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Yes')]")
        f.write('\n')
        f.write("    closeSoftTokenSwitchElement_Cancel:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '取消')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '取消')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Cancel')]")
        f.write('\n')
        f.write("    #流动保安编码设置成功页面元素")
        f.write('\n')
        f.write("    softTokenSettingsSuccessElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '你已成功启用流动保安编码！')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '你已成功啟用流動保安編碼！')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Your Soft Token has been activated successfully!')]")
        f.write('\n')
        f.write("    #版本更新按钮")
        f.write('\n')
        f.write("    versionUpdateElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '版本更新')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '版本更新')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Version Update')]")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("  ios:")
        f.write('\n')
        f.write("    #语言下拉框")
        f.write('\n')
        f.write("    languageElement: //XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[3]/XCUIElementTypeOther[2]")
        f.write('\n')
        f.write("    #语言选择")
        f.write('\n')
        f.write("    EnglishElement: //*[contains(@name, 'English')]")
        f.write('\n')
        f.write("    SimplifiedChineseElement: //*[contains(@name, '简体中文')]")
        f.write('\n')
        f.write("    TraditionalChineseElement: //*[contains(@name, '繁體中文')]")
        f.write('\n')
        f.write("    #通知按钮")
        f.write('\n')
        f.write("    notificationsElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '通知')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '通知')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Notifications')]")
        f.write('\n')
        f.write("    #登录设置按钮")
        f.write('\n')
        f.write("    loginSettingsElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '登录设置')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '登入設定')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Login Settings')]")
        f.write('\n')
        f.write("    #更改登录密码")
        f.write('\n')
        f.write("    Changeloginpassword:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '更改登录密码')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '更改登入密碼')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Change Login Password')]")
        f.write('\n')
        f.write("    #流动保安编码按钮")
        f.write('\n')
        f.write("    softTokenSettingsElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '流动保安编码')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '流動保安編碼')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Soft Token')]")
        f.write('\n')
        f.write("    #流动保安编码开关元素")
        f.write('\n')
        f.write("    softTokenSwitchElement: //XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[3]/XCUIElementTypeSwitch")
        f.write('\n')
        f.write("    #关闭保安流动编码弹窗确认元素")
        f.write('\n')
        f.write("    closeSoftTokenSwitchElement_YES:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '是')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '是')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Yes')]")
        f.write('\n')
        f.write("    closeSoftTokenSwitchElement_Cancel:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '取消')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '取消')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Cancel')]")
        f.write('\n')
        f.write("    #流动保安编码设置成功页面元素")
        f.write('\n')
        f.write("    softTokenSettingsSuccessElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '你已成功启用流动保安编码！')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '你已成功啟用流動保安編碼！')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Your Soft Token has been activated successfully!')]")
        f.write('\n')
        f.write("    #版本更新按钮")
        f.write('\n')
        f.write("    versionUpdateElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '版本更新')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '版本更新')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Version Update')]")
        f.write('\n')
    with open(os.path.join(path, 'HomeElement.yaml'), 'w', encoding="utf-8") as f:
        f.write("#首页元素")
        f.write('\n')
        f.write("HomePage:")
        f.write('\n')
        f.write("  android:")
        f.write('\n')
        f.write("    #提示页按钮")
        f.write('\n')
        f.write("    tipsButtonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '明白了！')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '明白了！')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Got It!')]")
        f.write('\n')
        f.write("    #登录页的问候语")
        f.write('\n')
        f.write("    greetingsElement: //android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]")
        f.write('\n')
        f.write("    #右上角的个人中心头像")
        f.write('\n')
        f.write("    personalCenterElement: ${greetingsElement}/android.widget.ImageView[3]")
        f.write('\n')
        f.write("    #通知弹窗确认按钮")
        f.write('\n')
        f.write("    notificationPopupElemnt:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '确认')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '確認')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'OK')]")
        f.write('\n')
        f.write("    #导肮头")
        f.write('\n')
        f.write("    #liviSave按钮")
        f.write('\n')
        f.write("    liviSaveElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '存款')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, 'liviSave')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'liviSave')]")
        f.write('\n')
        f.write("    #paylater按钮")
        f.write('\n')
        f.write("    paylaterElement: //*[contains(@content-desc, 'PayLater')]")
        f.write('\n')
        f.write("    #Loan按钮")
        f.write('\n')
        f.write("    LoanElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '贷款')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '貸款')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Loan')]")
        f.write('\n')
        f.write("    #保险按钮")
        f.write('\n')
        f.write("    insuranceElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '保险')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '保險')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Insurance')]")
        f.write('\n')
        f.write("    #贷款按钮")
        f.write('\n')
        f.write("    loanElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '贷款')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '貸款')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Loan')]")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("    #账户余额")
        f.write('\n')
        f.write("    accountBalanceElemnet: //android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("    #页面底下三个按钮")
        f.write('\n')
        f.write("    #首页按钮")
        f.write('\n')
        f.write("    underHomeButtonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '主页')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '主頁')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Overview')]")
        f.write('\n')
        f.write("    #随你赏按钮")
        f.write('\n')
        f.write("    underHappinessButtonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '随你赏')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '隨你賞')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Happiness')]")
        f.write('\n')
        f.write("    #交易记录按钮")
        f.write('\n')
        f.write("    underTransactionsButtonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '交易纪录')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '交易紀錄')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Transactions')]")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("  ios:")
        f.write('\n')
        f.write("    #提示页按钮")
        f.write('\n')
        f.write("    tipsButtonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '明白了！')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '明白了！')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Got It!')]")
        f.write('\n')
        f.write("    #登录页的问候语")
        f.write('\n')
        f.write("    greetingsElement: //XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther")
        f.write('\n')
        f.write("    #右上角的个人中心头像")
        f.write('\n')
        f.write("    personalCenterElement: //XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeImage[3]")
        f.write('\n')
        f.write("    #通知弹窗确认按钮")
        f.write('\n')
        f.write("    notificationPopupElemnt:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '确认')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '確認')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'ok')]")
        f.write('\n')
        f.write("    #导肮头")
        f.write('\n')
        f.write("    #liviSave按钮")
        f.write('\n')
        f.write("    liviSaveElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '存款')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, 'liviSave')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'liviSave')]")
        f.write('\n')
        f.write("    #paylater按钮")
        f.write('\n')
        f.write("    paylaterElement: //*[contains(@name, 'PayLater')]")
        f.write('\n')
        f.write("    #保险按钮")
        f.write('\n')
        f.write("    insuranceElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '保险')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '保險')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Insurance')]")
        f.write('\n')
        f.write("    #贷款按钮")
        f.write('\n')
        f.write("    loanElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '贷款')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '貸款')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Loan')]")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("    #账户余额")
        f.write('\n')
        f.write("    accountBalanceElemnet: //android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[2]")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("    #页面底下三个按钮")
        f.write('\n')
        f.write("    #首页按钮")
        f.write('\n')
        f.write("    underHomeButtonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '主页')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '主頁')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Overview')]")
        f.write('\n')
        f.write("    #随你赏按钮")
        f.write('\n')
        f.write("    underHappinessButtonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '随你赏')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '隨你賞')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Happiness')]")
        f.write('\n')
        f.write("    #交易记录按钮")
        f.write('\n')
        f.write("    underTransactionsButtonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '交易纪录')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '交易紀錄')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Transactions')]")
        f.write('\n')
    with open(os.path.join(path, 'LoginElement.yaml'), 'w', encoding="utf-8") as f:
        f.write("#登录页元素")
        f.write('\n')
        f.write("LandingPage:")
        f.write('\n')
        f.write("  android:")
        f.write('\n')
        f.write("    #登录页的问候语言")
        f.write('\n')
        f.write("    languageElement: //android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.widget.Button[1]")
        f.write('\n')
        f.write("    PermissionWindowAllowsElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@text, '允许')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@text, '允許')]")
        f.write('\n')
        f.write("      English: //*[contains(@text, 'Allow')]")
        f.write('\n')
        f.write("    #更新弹窗")
        f.write('\n')
        f.write("    updateNotificationElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '取消')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '取消')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Cancel')]")
        f.write('\n')
        f.write("    #登录页右上角“...”的菜单元素")
        f.write('\n')
        f.write("    menuElement: //android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.widget.ImageView[3]")
        f.write('\n')
        f.write("    #切换用户的按钮")
        f.write('\n')
        f.write("    SwitchUserElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '切换用户')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '切換用戶')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Switch User')]")
        f.write('\n')
        f.write("    #手机号输入框")
        f.write('\n')
        f.write("    phoneInputElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@text, '手机号码')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@text, '手提電話號碼')]")
        f.write('\n')
        f.write("      English: //*[contains(@text, 'Mobile Number')]")
        f.write('\n')
        f.write("    #登录按钮")
        f.write('\n')
        f.write("    LoginButtonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[@content-desc='登录']")
        f.write('\n')
        f.write("      TraditionalChinese: //*[@content-desc='登入']")
        f.write('\n')
        f.write("      English: //*[@content-desc='Login']")
        f.write('\n')
        f.write("    #输入密码文本（通过点击这个文本收起键盘）")
        f.write('\n')
        f.write("    passwordTextElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '输入密码')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '輸入密碼')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Enter Your Password')]")
        f.write('\n')
        f.write("    #密码输入框")
        f.write('\n')
        f.write("    passwordInputElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@text, '密码')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@text, '密碼')]")
        f.write('\n')
        f.write("      English: //*[contains(@text, 'Password')]")
        f.write('\n')
        f.write("    #通知弹窗确认")
        f.write('\n')
        f.write("    notifyTipsElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '我们该如何通知你？')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '我們該如何通知你？')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'How shall we notify you?')]")
        f.write('\n')
        f.write("    #通知弹窗确认")
        f.write('\n')
        f.write("    notifyConfirmBottonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '完成')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '完成')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Done')]")
        f.write('\n')
        f.write("    #生物认证弹窗稍后决定按钮")
        f.write('\n')
        f.write("    BiometricCertificationBottonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '稍后决定')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '稍後决定')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Maybe Later')]")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("    #推送通知权限-保留通知权限按钮")
        f.write('\n')
        f.write("    KeepSMSNotificationsBottonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@content-desc, '保留短讯通知')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@content-desc, '保留短訊通知')]")
        f.write('\n')
        f.write("      English: //*[contains(@content-desc, 'Keep SMS Notifications')]")
        f.write('\n')
        f.write("")
        f.write('\n')
        f.write("  ios:")
        f.write('\n')
        f.write("    #登录页的问候语言")
        f.write('\n')
        f.write("    languageElement: //XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeButton")
        f.write('\n')
        f.write("    #更新弹窗")
        f.write('\n')
        f.write("    updateNotificationElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '取消')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '取消')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Cancel')]")
        f.write('\n')
        f.write("    #登录页右上角“...”的菜单元素")
        f.write('\n')
        f.write("    menuElement: //XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeImage[3]")
        f.write('\n')
        f.write("    #切换用户的按钮")
        f.write('\n')
        f.write("    SwitchUserElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '切换用户')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '切換用戶')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Switch User')]")
        f.write('\n')
        f.write("    #手机号输入框")
        f.write('\n')
        f.write("    phoneInputElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '手机号码')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '手提電話號碼')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Mobile Number')]")
        f.write('\n')
        f.write("    #登录按钮")
        f.write('\n')
        f.write("    LoginButtonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //XCUIElementTypeButton[@name='登录']")
        f.write('\n')
        f.write("      TraditionalChinese: //XCUIElementTypeButton[@name='登入']")
        f.write('\n')
        f.write("      English: //XCUIElementTypeButton[@name='Login']")
        f.write('\n')
        f.write("    #输入密码文本（通过点击这个文本收起键盘）")
        f.write('\n')
        f.write("    passwordTextElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '输入密码')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '輸入密碼')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Enter Your Password')]")
        f.write('\n')
        f.write("    #密码输入框")
        f.write('\n')
        f.write("    passwordInputElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //XCUIElementTypeTextField[@name='密码']")
        f.write('\n')
        f.write("      TraditionalChinese: //XCUIElementTypeTextField[@name='密碼']")
        f.write('\n')
        f.write("      English: //XCUIElementTypeTextField[@name='Password']")
        f.write('\n')
        f.write("    #通知弹窗确认")
        f.write('\n')
        f.write("    notifyTipsElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '我们该如何通知你？')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '密碼')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'How shall we notify you?')]")
        f.write('\n')
        f.write("    #通知弹窗确认")
        f.write('\n')
        f.write("    notifyConfirmBottonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '完成')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '完成')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Done')]")
        f.write('\n')
        f.write("    #生物认证弹窗稍后决定按钮")
        f.write('\n')
        f.write("    BiometricCertificationBottonElement:")
        f.write('\n')
        f.write("      SimplifiedChinese: //*[contains(@name, '稍后决定')]")
        f.write('\n')
        f.write("      TraditionalChinese: //*[contains(@name, '稍後决定')]")
        f.write('\n')
        f.write("      English: //*[contains(@name, 'Maybe Later')]")
        f.write('\n')


def get_yaml_example_of_web_element(path):
    with open(os.path.join(path, 'XXXElement.yaml'), 'w', encoding="utf-8") as f:
        f.write("#XXX页面元素")
        f.write('\n')
        f.write("#举个例子")
        f.write('\n')
        f.write("XXXPage:")
        f.write('\n')
        f.write("  LiviBankTextElement: //span[text()='Livi Bank']")
        f.write('\n')


def get_yaml_example_of_gherkin(path):
    with open(os.path.join(path, 'XXXSteps.yaml'), 'w', encoding="utf-8") as f:
        f.write("#web装置时，Fixture填写web；app装置时，Fixture填写app")
        f.write('\n')
        f.write("-")
        f.write('\n')
        f.write("  Step: Given")
        f.write('\n')
        f.write("  Text: 这里填写feature文件的Given语言")
        f.write('\n')
        f.write("  Fixture: web")
        f.write('\n')
        f.write("#这里填写操作过程，具体写法请参考手册")
        f.write('\n')
        f.write("  Process:")
        f.write('\n')
        f.write("      step1:")
        f.write('\n')
        f.write("        Action: click")
        f.write('\n')
        f.write("        Element: ${HomePage}${ApplicationSpanElement}")
        f.write('\n')
        f.write("        TestData:")
        f.write('\n')
        f.write("        Remarks: 点击Application")
        f.write('\n')
        f.write("-")
        f.write('\n')
        f.write("  Step: When")
        f.write('\n')
        f.write("  Text: 这里填写feature文件的When语言")
        f.write('\n')
        f.write("  Fixture: web")
        f.write('\n')
        f.write("#这里填写操作过程，具体写法请参考手册")
        f.write('\n')
        f.write("  Process:")
        f.write('\n')
        f.write("      step1:")
        f.write('\n')
        f.write("        Action: click")
        f.write('\n')
        f.write("        Element: ${HomePage}${ApplicationSpanElement}")
        f.write('\n')
        f.write("        TestData:")
        f.write('\n')
        f.write("        Remarks: 点击Application")
        f.write('\n')
        f.write("-")
        f.write('\n')
        f.write("  Step: And")
        f.write('\n')
        f.write("  Text: 这里填写feature文件的And语言")
        f.write('\n')
        f.write("  Fixture: web")
        f.write('\n')
        f.write("#这里填写操作过程，具体写法请参考手册")
        f.write('\n')
        f.write("  Process:")
        f.write('\n')
        f.write("      step1:")
        f.write('\n')
        f.write("        Action: click")
        f.write('\n')
        f.write("        Element: ${HomePage}${ApplicationSpanElement}")
        f.write('\n')
        f.write("        TestData:")
        f.write('\n')
        f.write("        Remarks: 点击Application")
        f.write('\n')
        f.write("-")
        f.write('\n')
        f.write("  Step: Then")
        f.write('\n')
        f.write("  Text: 这里填写feature文件的Then语言")
        f.write('\n')
        f.write("  Fixture: web")
        f.write('\n')
        f.write("#这里填写操作过程，具体写法请参考手册")
        f.write('\n')
        f.write("  Process:")
        f.write('\n')
        f.write("      step1:")
        f.write('\n')
        f.write("        Action: click")
        f.write('\n')
        f.write("        Element: ${HomePage}${ApplicationSpanElement}")
        f.write('\n')
        f.write("        TestData:")
        f.write('\n')
        f.write("        Remarks: 点击Application")
        f.write('\n')