#PayLater取消申请
-
  Step: Given
  Text: 取消PayLater申请
  Fixture: app
  Process:
    -
      Action: click
      Element: ${HomePage}${paylaterElement}
      TestData:
      Remarks: 点击首页-paylater卡片
    -
      Action: sleep
      Element:
      TestData: 5
      Remarks: 等待5秒
    -
      Action: judge,branch
      Element: ${LendingPayLaterHomeElement}${ViewOfferButtonElement}
      TestData:
      Remarks: 判断是否存在查看结果度按钮，若存在则走if分支
      ifbranchProcess:
        -
          Action: click
          Element: ${LendingPayLaterHomeElement}${ViewOfferButtonElement}
          TestData:
          Remarks: 点击查看结果
        -
          Action: sleep
          Element:
          TestData: 5
          Remarks: 等待5秒
        -
          Action: click
          Element: ${LendingPayLaterApplicationApproved}${CancelApplicationElement}
          TestData:
          Remarks: 额度确认页面，点击关闭按钮
        -
          Action: click
          Element: ${LendingPayLaterApplicationApproved}${CancelApplicationButtonElement}
          TestData:
          Remarks: 点击取消额度申请按钮
        -
          Action: sleep
          Element:
          TestData: 8
          Remarks: 等待8秒
        -
          Action: judge,branch
          Element: ${LendingPayLaterHomeElement}${ViewOfferButtonElement}
          TestData:
          Remarks: 判断是否存在查看结果度按钮，若存在则走if分支
          ifbranchProcess:
            -
              Action: sleep
              Element:
              TestData: 2
              Remarks: 取消额度失败，需检查原因
          elsebranchProcess:
            -
              Action: sleep
              Element:
              TestData: 2
              Remarks: 取消额度成功
      elsebranchProcess:
        - Action: sleep
          Element:
          TestData: 5
          Remarks: 等待5秒
-
  Step: Then
  Text: 我看不到查看结果
  Fixture: app
  Process:
    -
      Action: judge
      Element: ${LendingPayLaterHomeElement}${ViewOfferButtonElement}
      TestData: false
      Remarks: 判断是否存在查看结果

-
  Step: Given
  Text: 我能看到web端该额度状态为未生效
  Fixture: web
  Process:
    -
      Action: sleep
      Element:
      TestData: 2
      Remarks: 等待2秒
    -
      Action: mouse
      Element: ${LendingElement}${PostLoanManagementElement}
      TestData: hover
      Remarks: 将鼠标悬停在指定元素上-贷后管理
    -
      Action: click
      Element: //*[@id='main_menu']/ul/li[9]/ul/li[1]/a/span[2]
      TestData:
      Remarks: 点击额度管理
    -
      Action: sleep
      Element:
      TestData: 2
      Remarks: 等待2秒
    -
      Action: iframe
      Element: //*[@id='main_bottom']/div/iframe
      TestData:
      Remarks: 切入表单
    -
      Action: click
      Element: //*[@id='handle_right0']/span[2]/a
      TestData:
      Remarks: 点击额度台账
    -
      Action: iframe
      Element: //*[@id='tabT01right0']
      TestData:
      Remarks: 切入表单
    -
      Action: sleep
      Element:
      TestData: 1
      Remarks: 等待1秒
    -
      Action: click
      Element: //*[@id='TH_Left_myiframe0']/tr/th[1]/div
      TestData:
      Remarks: 点击搜索
    -
      Action: input
      Element: //*[@id='DOFILTER_MAIN1_CUSTOMERID']/input
      TestData: ${Lending}${CustomerId}
      Remarks: 输入客户号
    -
      Action: click
      Element: //*[@id='DOFILTER_MAIN1_BUSINESSTYPE']/span[1]
      TestData:
      Remarks: 点击基础产品
    -
      Action: sleep
      Element:
      TestData: 1
      Remarks: 等待1秒
    -
      Action: click
      Element: //a[text()='livi PayLater']
      TestData:
      Remarks: 选择livi PayLater
#    -
#      Action: click
#      Element: //*[@id='DOFILTER_MAIN1_LIMIT_STATUS']
#      TestData:
#      Remarks: 点击额度状态
#    -
#      Action: click
#      Element: //a[text()='已终止']
#      TestData:
#      Remarks: 选择额度状态为-已终止
    -
      Action: click
      Element: //*[@id='TableFilter_AREA']/div[2]/table/tbody/tr/td/input[1]
      TestData:
      Remarks: 点击确定
    -
      Action: get_text
      Element: //*[@id='INPUT_myiframe0_SerialNo_0_0']
      TestData: $${LimitSerialno}
      Remarks: 获取额度编号
    -
      Action: get
      Element: //*[@id='INPUT_myiframe0_LIMIT_STATUS_0_10']
      TestData: '未生效'
      Remarks: 断言，判断额度状态是否终止
    -
      Action: sleep
      Element:
      TestData: 3
      Remarks: 等待3秒

