'''
填充Given段落的steps
'''
from common.getAppFormat import appFormat
from common.getVariable import get_system
from common.getWebFormat import webFormat
from common.getSteps import get_steps


def fill_Given_Paragraph(f,paragraph):
    f.write('@given("'+paragraph['Text']+'")')
    f.write('\n')
    var = ''
    if paragraph['Text'].count('{') >= 1:
        for i in paragraph['Text'].split('{'):
            if '}' in i:
                var = var + ',' + i.split('}')[0]
        f.write('def step_impl(context' + var + '):')
        f.write('\n')
    else:
        f.write('def step_impl(context):')
        f.write('\n')
    if '启动了web装置' in paragraph['Text'] and str(paragraph['Fixture']).lower() == 'web':
        f.write('    if gloVar.browserContext is None:')
        f.write('\n')
        f.write('        use_fixture(selenium_browser_chrome, context)')
        f.write('\n')
        f.write('        gloVar.browserContext = context.browser')
        f.write('\n')
        f.write('        gloVar.browserContext.openBrowser()')
        f.write('\n')
    elif '启动了web装置' not in paragraph['Text'] and str(paragraph['Fixture']).lower() == 'web':
        webFormat(f, get_steps(paragraph['Process']), '')
    elif '启动了app装置' in paragraph['Text'] and str(paragraph['Fixture']).lower() == 'app' and '同时' not in paragraph['Text']:
        f.write('    if gloVar.driverContext is None:')
        f.write('\n')
        f.write('        use_fixture(appium_device_app, context)')
        f.write('\n')
        f.write('        gloVar.driverContext = context.driver')
        f.write('\n')
        if get_system() == 'Windows':
            f.write('        gloVar.p = gloVar.driverContext.Start_recording_screen("LiviBank_App_")')
            f.write('\n')
        f.write('        APP_PARAMETER_YAML = get_app_parameter_yaml_path(ISYAML,PROJECT)')
        f.write('\n')
        f.write('        parameter = YamlReader(APP_PARAMETER_YAML).data[0]')
        f.write('\n')
        f.write('        gloVar.platformName = parameter["desired_caps"]["platformName"]')
        f.write('\n')
        f.write('        version = parameter["Version"]')
        f.write('\n')
        f.write('        autoLaunch = parameter["desired_caps"]["autoLaunch"]')
        f.write('\n')
        f.write('        noReset = parameter["desired_caps"]["noReset"]')
        f.write('\n')
        if '第一次打开app' in paragraph['Text']:
            f.write('        if str(gloVar.platformName).lower() == "ios":')
            f.write('\n')
            f.write('            gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow'" + ']",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow'" + ']",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'允许'" + ']",gloVar.platformName,"None"),"判断是否存在定位授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'允许'" + ']",gloVar.platformName,"None"),"None","判断是否存在定位授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'允許'" + ']",gloVar.platformName,"None"),"判断是否存在定位授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'允許'" + ']",gloVar.platformName,"None"),"None","判断是否存在定位授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'使用App時允許'" + ']",gloVar.platformName,"None"),"判断是否存在跟踪授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'使用App時允許'" + ']",gloVar.platformName,"None"),"None","判断是否存在跟踪授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'使用App时允许'" + ']",gloVar.platformName,"None"),"判断是否存在跟踪授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'使用App时允许'" + ']",gloVar.platformName,"None"),"None","判断是否存在跟踪授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow While Using App'" + ']",gloVar.platformName,"None"),"判断是否存在跟踪授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow While Using App'" + ']",gloVar.platformName,"None"),"None","判断是否存在跟踪授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow'" + ']",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow'" + ']",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
        f.write('        if str(gloVar.platformName).lower() == "android":')
        f.write('\n')
        f.write('            if autoLaunch:')
        f.write('\n')
        f.write('                if version:')
        f.write('\n')
        if '第一次打开app' in paragraph['Text']:
            f.write('                    if str(gloVar.platformName).lower() == "android":')
            f.write('\n')
            f.write('                        gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                        if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@text, ' + "'Continue'" + ')]",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                            gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@text, ' + "'Continue'" + ')]",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                            logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                            for i in range(10):')
            f.write('\n')
            f.write('                                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'Login'" + ')]",gloVar.platformName,"None"),"判断是否存在Login按钮失败截图"):')
            f.write('\n')
            f.write('                                    break')
            f.write('\n')
            f.write('                                gloVar.driverContext.initializationApp(1)')
            f.write('\n')
            f.write('                                gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                            gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('                        gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                        if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@text, ' + "'继续'" + ')]",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                            gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@text, ' + "'继续'" + ')]",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                            logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                            for i in range(10):')
            f.write('\n')
            f.write('                                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'登录'" + ')]",gloVar.platformName,"None"),"判断是否存在登录按钮失败截图"):')
            f.write('\n')
            f.write('                                    break')
            f.write('\n')
            f.write('                                gloVar.driverContext.initializationApp(1)')
            f.write('\n')
            f.write('                                gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                            gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('                    gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                    logger.info("判断是否第一次登陆app，如果是第一次登陆点击右上角登陆按钮")')
            f.write('\n')
            f.write('                    if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'申请贷款'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
            f.write('\n')
            f.write('                        gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'登录'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
            f.write('\n')
            f.write('                    if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'申請貸款'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
            f.write('\n')
            f.write('                        gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'登入'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
            f.write('\n')
            f.write('                    if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'Apply for a Loan'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
            f.write('\n')
            f.write('                        gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'Login'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
            f.write('\n')
            f.write('                    gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
        f.write('                    gloVar.driverContext = gloVar.driverContext.Science(parameter["Science"],gloVar.platformName,version)')
        f.write('\n')
        f.write('                else:')
        f.write('\n')
        f.write('                    gloVar.driverContext.Science(parameter["Science"],gloVar.platformName)')
        f.write('\n')
        f.write('        else:')
        f.write('\n')
        f.write('            if noReset is False:')
        f.write('\n')
        if '第一次打开app' in paragraph['Text']:
            f.write('                if str(gloVar.platformName).lower() == "android":')
            f.write('\n')
            f.write('                     gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                     if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@text, ' + "'Continue'" + ')]",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                         gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@text, ' + "'Continue'" + ')]",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                         logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                         gloVar.driverContext.initializationApp()')
            f.write('\n')
            f.write('                         gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('                     gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                     if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@text, ' + "'继续'" + ')]",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                         gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@text, ' + "'继续'" + ')]",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                         logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                         gloVar.driverContext.initializationApp()')
            f.write('\n')
            f.write('                         gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
        f.write('                gloVar.driverContext.Science(parameter["Science"],gloVar.platformName)')
        f.write('\n')
        f.write('        if str(gloVar.platformName).lower() == "ios":')
        f.write('\n')
        f.write('            if noReset is False:')
        f.write('\n')
        f.write('                gloVar.driverContext.sleepOperation("sleep","3","停顿3秒")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeButton[2]",gloVar.platformName,"None"),"判断是否存在提示更新弹窗失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeButton[2]",gloVar.platformName,"None"),"None","判断是否存在提示更新弹窗点击取消失败截图")')
        f.write('\n')
        f.write('                    gloVar.driverContext.sleepOperation("sleep","3","停顿3秒")')
        f.write('\n')
        f.write('                logger.info("判断是否第一次登陆app，如果是第一次登陆点击右上角登陆按钮")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'申请贷款'" + ']",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'登录'" + ']",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'申請貸款'" + ']",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'登入'" + ']",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Apply for a Loan'" + ']",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Login'" + ']",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('        else:')
        f.write('\n')
        f.write('            if autoLaunch:')
        f.write('\n')
        f.write('                gloVar.driverContext.sleepOperation("sleep","3","停顿3秒")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'取消'" + ')]",gloVar.platformName,"None"),"判断是否存在提示更新弹窗失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'取消'" + ')]",gloVar.platformName,"None"),"None","判断是否存在提示更新弹窗点击取消失败截图")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'Cancel'" + ')]",gloVar.platformName,"None"),"判断是否存在提示更新弹窗失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'Cancel'" + ')]",gloVar.platformName,"None"),"None","判断是否存在提示更新弹窗点击取消失败截图")')
        f.write('\n')
        f.write('                gloVar.driverContext.sleepOperation("sleep","3","停顿3秒")')
        f.write('\n')
        f.write('                logger.info("判断是否第一次登陆app，如果是第一次登陆点击右上角登陆按钮")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'申请贷款'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'登录'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'申請貸款'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'登入'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'Apply for a Loan'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'Login'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('        gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
        f.write('\n')
        f.write('        if str(gloVar.platformName).lower() == "android":')
        f.write('\n')
        f.write('            if autoLaunch:')
        f.write('\n')
        f.write('                gloVar.language = gloVar.driverContext.judgeLanguage(get_App_Element_variable("${LandingPage}${languageElement}",gloVar.platformName),gloVar.platformName)')
        f.write('\n')
        f.write('            else:')
        f.write('\n')
        f.write('                gloVar.language = parameter["language"]')
        f.write('\n')
        f.write('        else:')
        f.write('\n')
        f.write('            if noReset:')
        f.write('\n')
        f.write('                gloVar.language = parameter["language"]')
        f.write('\n')
        f.write('            else:')
        f.write('\n')
        f.write('                gloVar.language = gloVar.driverContext.judgeLanguage(get_App_Element_variable("${LandingPage}${languageElement}",gloVar.platformName),gloVar.platformName)')
        f.write('\n')
    elif '启动了app装置' not in paragraph['Text'] and str(paragraph['Fixture']).lower() == 'app':
        appFormat(f, get_steps(paragraph['Process']), '')
    elif '同时启动了' in paragraph['Text'] and  ('web、app' in paragraph['Text'] or 'app、web' in paragraph['Text']) and '装置' in paragraph['Text']:
        f.write('    if gloVar.browserContext is None:')
        f.write('\n')
        f.write('        use_fixture(selenium_browser_chrome, context)')
        f.write('\n')
        f.write('        gloVar.browserContext = context.browser')
        f.write('\n')
        f.write('        gloVar.browserContext.openBrowser()')
        f.write('\n')
        f.write('    if gloVar.driverContext is None:')
        f.write('\n')
        f.write('        use_fixture(appium_device_app, context)')
        f.write('\n')
        f.write('        gloVar.driverContext = context.driver')
        f.write('\n')
        if get_system() == 'Windows':
            f.write('        gloVar.p = gloVar.driverContext.Start_recording_screen("LiviBank_App_")')
            f.write('\n')
        f.write('        APP_PARAMETER_YAML = get_app_parameter_yaml_path(ISYAML,PROJECT)')
        f.write('\n')
        f.write('        parameter = YamlReader(APP_PARAMETER_YAML).data[0]')
        f.write('\n')
        f.write('        gloVar.platformName = parameter["desired_caps"]["platformName"]')
        f.write('\n')
        f.write('        version = parameter["Version"]')
        f.write('\n')
        f.write('        autoLaunch = parameter["desired_caps"]["autoLaunch"]')
        f.write('\n')
        f.write('        noReset = parameter["desired_caps"]["noReset"]')
        f.write('\n')
        if '第一次打开app' in paragraph['Text']:
            f.write('        if str(gloVar.platformName).lower() == "ios":')
            f.write('\n')
            f.write('            gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow'" + ']",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow'" + ']",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'允许'" + ']",gloVar.platformName,"None"),"判断是否存在定位授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'允许'" + ']",gloVar.platformName,"None"),"None","判断是否存在定位授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'允許'" + ']",gloVar.platformName,"None"),"判断是否存在定位授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'允許'" + ']",gloVar.platformName,"None"),"None","判断是否存在定位授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'使用App時允許'" + ']",gloVar.platformName,"None"),"判断是否存在跟踪授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'使用App時允許'" + ']",gloVar.platformName,"None"),"None","判断是否存在跟踪授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'使用App时允许'" + ']",gloVar.platformName,"None"),"判断是否存在跟踪授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'使用App时允许'" + ']",gloVar.platformName,"None"),"None","判断是否存在跟踪授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow While Using App'" + ']",gloVar.platformName,"None"),"判断是否存在跟踪授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow While Using App'" + ']",gloVar.platformName,"None"),"None","判断是否存在跟踪授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('            if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow'" + ']",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Allow'" + ']",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
        f.write('        if str(gloVar.platformName).lower() == "android":')
        f.write('\n')
        f.write('            if autoLaunch:')
        f.write('\n')
        f.write('                if version:')
        f.write('\n')
        if '第一次打开app' in paragraph['Text']:
            f.write('                    if str(gloVar.platformName).lower() == "android":')
            f.write('\n')
            f.write('                        gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                        if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@text, ' + "'Continue'" + ')]",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                            gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@text, ' + "'Continue'" + ')]",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                            logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                            gloVar.driverContext.initializationApp()')
            f.write('\n')
            f.write('                            gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('                        gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                        if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@text, ' + "'继续'" + ')]",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                            gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@text, ' + "'继续'" + ')]",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                            logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                            gloVar.driverContext.initializationApp()')
            f.write('\n')
            f.write('                            gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('                    gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                    logger.info("判断是否第一次登陆app，如果是第一次登陆点击右上角登陆按钮")')
            f.write('\n')
            f.write('                    if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'申请贷款'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
            f.write('\n')
            f.write('                        gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'登录'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
            f.write('\n')
            f.write('                    if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'申請貸款'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
            f.write('\n')
            f.write('                        gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'登入'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
            f.write('\n')
            f.write('                    if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'Apply for a Loan'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
            f.write('\n')
            f.write('                        gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'Login'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
            f.write('\n')
            f.write('                    gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
        f.write('                    gloVar.driverContext = gloVar.driverContext.Science(parameter["Science"],gloVar.platformName,version)')
        f.write('\n')
        f.write('                else:')
        f.write('\n')
        f.write('                    gloVar.driverContext.Science(parameter["Science"],gloVar.platformName)')
        f.write('\n')
        f.write('        else:')
        f.write('\n')
        f.write('            if noReset is False:')
        f.write('\n')
        if '第一次打开app' in paragraph['Text']:
            f.write('                if str(gloVar.platformName).lower() == "android":')
            f.write('\n')
            f.write('                     gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                     if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@text, ' + "'Continue'" + ')]",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                         gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@text, ' + "'Continue'" + ')]",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                         logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                         gloVar.driverContext.initializationApp()')
            f.write('\n')
            f.write('                         gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('                     gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
            f.write('                     if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@text, ' + "'继续'" + ')]",gloVar.platformName,"None"),"判断是否存在授权弹窗失败截图"):')
            f.write('\n')
            f.write('                         gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@text, ' + "'继续'" + ')]",gloVar.platformName,"None"),"None","判断是否存在授权弹窗点击授权失败截图")')
            f.write('\n')
            f.write('                         logger.info("检测到首次登录app，需对手机进行授权确认")')
            f.write('\n')
            f.write('                         gloVar.driverContext.initializationApp()')
            f.write('\n')
            f.write('                         gloVar.driverContext.sleepOperation("sleep","2","停顿2秒")')
            f.write('\n')
            f.write('                gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
            f.write('\n')
        f.write('                gloVar.driverContext.Science(parameter["Science"],gloVar.platformName)')
        f.write('\n')
        f.write('        if str(gloVar.platformName).lower() == "ios":')
        f.write('\n')
        f.write('            if noReset is False:')
        f.write('\n')
        f.write('                gloVar.driverContext.sleepOperation("sleep","3","停顿3秒")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeButton[2]",gloVar.platformName,"None"),"判断是否存在提示更新弹窗失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeButton[2]",gloVar.platformName,"None"),"None","判断是否存在提示更新弹窗点击取消失败截图")')
        f.write('\n')
        f.write('                    gloVar.driverContext.sleepOperation("sleep","3","停顿3秒")')
        f.write('\n')
        f.write('                logger.info("判断是否第一次登陆app，如果是第一次登陆点击右上角登陆按钮")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'申请贷款'" + ']",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'登录'" + ']",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'申請貸款'" + ']",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'登入'" + ']",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Apply for a Loan'" + ']",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//XCUIElementTypeButton[@name=' + "'Login'" + ']",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('        else:')
        f.write('\n')
        f.write('            if autoLaunch:')
        f.write('\n')
        f.write('                gloVar.driverContext.sleepOperation("sleep","3","停顿3秒")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'取消'" + ')]",gloVar.platformName,"None"),"判断是否存在提示更新弹窗失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'取消'" + ')]",gloVar.platformName,"None"),"None","判断是否存在提示更新弹窗点击取消失败截图")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'Cancel'" + ')]",gloVar.platformName,"None"),"判断是否存在提示更新弹窗失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'Cancel'" + ')]",gloVar.platformName,"None"),"None","判断是否存在提示更新弹窗点击取消失败截图")')
        f.write('\n')
        f.write('                gloVar.driverContext.sleepOperation("sleep","3","停顿3秒")')
        f.write('\n')
        f.write('                logger.info("判断是否第一次登陆app，如果是第一次登陆点击右上角登陆按钮")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'申请贷款'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'登录'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'申請貸款'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'登入'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('                if gloVar.driverContext.judgeOperation("judge",get_App_Element_variable("//*[contains(@content-desc, ' + "'Apply for a Loan'" + ')]",gloVar.platformName,"None"),"判断是否首次登陆，右上角登陆按钮是否存在失败截图"):')
        f.write('\n')
        f.write('                    gloVar.driverContext.clickOperation("click",get_App_Element_variable("//*[contains(@content-desc, ' + "'Login'" + ')]",gloVar.platformName,"None"),"None","判断是否首次登陆，右上角登陆按钮是否存在失败截图")')
        f.write('\n')
        f.write('        gloVar.driverContext.sleepOperation("sleep","5","停顿5秒")')
        f.write('\n')
        f.write('        if str(gloVar.platformName).lower() == "android":')
        f.write('\n')
        f.write('            if autoLaunch:')
        f.write('\n')
        f.write('                gloVar.language = gloVar.driverContext.judgeLanguage(get_App_Element_variable("${LandingPage}${languageElement}",gloVar.platformName),gloVar.platformName)')
        f.write('\n')
        f.write('            else:')
        f.write('\n')
        f.write('                gloVar.language = parameter["language"]')
        f.write('\n')
        f.write('        else:')
        f.write('\n')
        f.write('            if noReset:')
        f.write('\n')
        f.write('                gloVar.language = parameter["language"]')
        f.write('\n')
        f.write('            else:')
        f.write('\n')
        f.write('                gloVar.language = gloVar.driverContext.judgeLanguage(get_App_Element_variable("${LandingPage}${languageElement}",gloVar.platformName),gloVar.platformName)')
        f.write('\n')
