def fill_library(f):
    f.write('import atexit')
    f.write('\n')
    f.write('from common.getPath import get_app_parameter_yaml_path')
    f.write('\n')
    f.write('from common.globalVar import gloVar')
    f.write('\n')
    f.write('from datetime import date')
    f.write('\n')
    f.write('from behave import given, use_fixture, then, step, when')
    f.write('\n')
    f.write('from decimal import Decimal')
    f.write('\n')
    f.write('from common.getVariable import get_variable, get_web_Element_variable, get_App_Element_variable, del_string,get_time_stamp,is_variable, check_time_format, get_time_value')
    f.write('\n')
    f.write('from featuresYaml.environment import selenium_browser_chrome, appium_device_app')
    f.write('\n')
    f.write('from common.logger import logger')
    f.write('\n')
    f.write('from page.webPage import Page')
    f.write('\n')
    f.write('from utils.file_read import YamlReader')
    f.write('\n')
    f.write('from config.Project import ISYAML, PROJECT')
    f.write('\n')
