def fill_Quit_Paragraph(f):
    f.write("@atexit.register")
    f.write('\n')
    f.write("def quit():")
    f.write('\n')
    f.write("    try:")
    f.write('\n')
    f.write("        gloVar.driverContext.quit()")
    f.write('\n')
    f.write("        gloVar.driverContext.Stop_recording_screen(gloVar.p)")
    f.write('\n')
    f.write("    except Exception:")
    f.write('\n')
    f.write("        pass")
    f.write('\n')
    f.write("    try:")
    f.write('\n')
    f.write("        gloVar.browserContext.quit()")
    f.write('\n')
    f.write("    except Exception:")
    f.write('\n')
    f.write("        pass")
    f.write('\n')